version: '3'
services:
  jamovi-deps:
    image: jamovi/jamovi-deps
    build:
      context: .
      dockerfile: docker/deps-Dockerfile
    profiles:
      - donotstart

  jamovi:
    container_name: jamovi
    build:
      context: .
      dockerfile: docker/jamovi-Dockerfile
    image: jamovi/jamovi
    ports:
      - '41337:41337'
      - '41338:41338'
      - '41339:41339'
    command: ["/usr/bin/python3 -m jamovi.server 41337 --if=*"]
    stdin_open: true
    environment:
        JAMOVI_HOSTNAME: '127.0.0.1'

    volumes:
      - $HOME/Documents:/root/Documents
      #- ./:/tmp/source  # mount the source as a volume for development
